# Generated by Django 5.0.6 on 2024-12-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_order_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_status',
        ),
    ]
