# Generated by Django 5.0.6 on 2024-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_payment_status_order_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
