# Generated by Django 5.0.6 on 2024-12-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_wishlist_unique_together_wishlist_size_variant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
