# Generated by Django 5.0.6 on 2024-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
